[package]
name = "eva-svc-filewriter"
version = "4.0.2"
edition = "2021"

[dependencies]
busrt = { version = "0.4", features = ["rpc", "ipc"] }
eva-common = { version = "0.3.7", features = ["events", "time", "common-payloads"] }
eva-sdk = { version = "0.3.4" }
tokio = { version = "1.20.1", features = ["full"] }
async-trait = { version = "0.1.51" }
serde = { version = "1.0.143", features = ["derive", "rc"] }
log = "0.4.14"
async-channel = "1.7.1"
serde_json = "1.0.79"
chrono = "0.4.19"
once_cell = "1.9.0"
jemallocator = { version = "0.5.0" }
cron = "0.11.0"
parking_lot = "0.12.1"
openssl = "0.10.42"

[features]
std-alloc = []
openssl-vendored = ["openssl/vendored"]
