[package]
name = "eva-svc-modbus-slave"
version = "4.0.0"
edition = "2021"

[dependencies]
eva-common = { version = "0.1.186", features = ["events", "time"] }
eva-sdk = { version = "0.1.112" }
tokio = { version = "1.20.1", features = ["full"] }
async-trait = { version = "0.1.51" }
serde = { version = "1.0.143", features = ["derive", "rc"] }
log = "0.4.14"
lazy_static = "1.4.0"
async-channel = "1.7.1"
jemallocator = { version = "0.5.0" }
rmodbus = "0.6.0"
tokio-serial = "5.4.3"
once_cell = "1.9.0"

[features]
std-alloc = []
