# worker threads (max recommended = number of CPUs)
workers: 1
# the default timeout
timeout: 5
# the suicide timeout, used during shutdown (the node process is forcibly
# killed after)
suicide_timeout: 15
# auto-create items coming from controllers (svc ids *.controller.* or *.plc.*)
auto_create: true
# instantly save item states
instant_save: true
# keep action history in memory (seconds)
keep_action_history: 86400
# core process memory usage warning (bytes), the default is 128 MiB per worker
#mem_warn: 134217728
# optional inventory database (for huge projects)
# NOTE: MySQL support is deprecated, use SQLite or PostgreSQL only
#inventory_db: postgres://USER:PASSWORD@HOST/DB
