# worker threads (max recommended = number of CPUs)
workers: 2
# the default timeout
timeout: 5
# the suicide timeout, used during shutdown (the node process is forcibly
# killed after)
suicide_timeout: 15
# instantly save item states
instant_save: true
# keep action history in memory (seconds)
keep_action_history: 86400
# optional inventory database (for huge projects)
# SQLite:
#inventory_db: sqlite:///opt/eva4/var/inventory.db
# MySQL:
#inventory_db: mysql://USER:PASSWORD@HOST/DB
# PostgreSQL
#inventory_db: postgres://USER:PASSWORD@HOST/DB
