[package]
name = "gen-intl"
version.workspace = true
edition.workspace = true
repository.workspace = true
publish = false

[dependencies]
serde_yaml = { workspace = true }
eva-common = { workspace = true }
clap = { features = ["derive"] , workspace = true }
colored = { workspace = true }
