[package]
name = "eva-filemgr"
version = "4.0.0"
edition = "2021"

[dependencies]
eva-common = { version = "0.1.178", features = ["events", "time"] }
eva-sdk = { version = "0.1.106" }
tokio = { version = "1.20.1", features = ["full"] }
async-trait = { version = "0.1.51" }
serde = { version = "1.0.143", features = ["derive", "rc"] }
log = "0.4.14"
lazy_static = "1.4.0"
once_cell = "1.13.0"
async-channel = "1.7.1"
serde_yaml = "0.8.26"
sha2 = "0.10.1"
hex = "0.4.3"
parse_int = "0.6.0"
jemallocator = { version = "0.5.0" }
tempfile = "3.3.0"
bmart = "0.2.4"

[features]
std-alloc = []
