[workspace]

members = [
  "eva",
  #"svc/svc-template",
  "svc/svc-example-temp",
  "svc/svc-example-sensor-set",
  "svc/dapp",
  "svc/db-influx",
  "svc/db-sql",
  "svc/db-timescale",
  "svc/aaa-acl",
  "svc/aaa-otp",
  "svc/aaa-localauth",
  "svc/svc-expiration",
  "svc/filemgr",
  "svc/svc-filewriter",
  "svc/controller-enip",
  "svc/controller-modbus",
  "svc/controller-ads",
  "svc/controller-opcua",
  "svc/controller-pubsub",
  "svc/bridge-ads",
  "svc/controller-w1",
  "svc/controller-trap",
  "svc/controller-sr",
  "svc/controller-virtual",
  "svc/controller-lm",
  "svc/svc-modbus-slave",
  "svc/hmi",
  "svc/ffi",
  "svc/mirror",
  "svc/repl",
  "svc/generator",
  "svc/svc-locker",
  "svc/svc-mailer",
  "tools/eva-cloud-manager",
  "tools/gen-intl",
  "psrpc",
  "genpass-native",
  "benchmarks/bm-primary"
]

resolver = "1"

exclude = [
  "contrib/webinfo"
]

[profile.release]
strip = true
lto = true
codegen-units = 1
