client:
  server_url: http://localhost:7555/
  #fips: true
  auth:
    name: test
    key: xxx
report:
  system:
    enabled: true
  # cpu info
  cpu:
    enabled: false
  # system load average
  load_avg:
    enabled: true
  # memory info
  memory:
    enabled: false
  # disk info
  disks:
    enabled: true
    # enable specific mount points only
    # note: for automatic mountpoint list reporting unavailable is not supported
    mount_points:
      - /
      #- /var
  blk:
    enabled: true
    # enable specific mount points only
    # note: for automatic mountpoint list reporting unavailable is not supported
    devices:
      - nvme1n1
  # network info
  network:
    enabled: false
    # enable specific interfaces only
    # note: for automatic interface list reporting unavailable is not supported
    #interfaces:
      #- eth0
      #- eth1
