client:
  server_url: http://127.0.0.1:7555
  #fips: true
  auth:
    name: test
    key: xxx
    #store: Trust
    #cert: mws1
report:
  system:
    enabled: true
  # cpu info
  cpu:
    enabled: false
  # system load average
  load_avg:
    enabled: true
  # memory info
  memory:
    enabled: false
  # disk info
  disks:
    enabled: true
    # enable specific mount points only
    # note: for automatic mountpoint list reporting unavailable is not supported
    mount_points:
      - /
      #- /var
  #blk:
    #enabled: true
    # enable specific mount points only
    # note: for automatic mountpoint list reporting unavailable is not supported
    #devices:
      #- nvme1n1
  # network info
  network:
    enabled: false
    # enable specific interfaces only
    # note: for automatic interface list reporting unavailable is not supported
    #interfaces:
      #- eth0
      #- eth1
