[package]
name = "eva-svc-mailer"
version = "4.0.0"
edition = "2021"

[dependencies]
eva-common = { version = "0.1.186", features = ["events", "time"] }
eva-sdk = { version = "0.1.112" }
tokio = { version = "1.20.1", features = ["full"] }
async-trait = { version = "0.1.51" }
serde = { version = "1.0.143", features = ["derive", "rc"] }
log = "0.4.14"
lettre = { version = "0.10.1", features = ["tokio1-native-tls"] }
jemallocator = { version = "0.5.0" }

[features]
std-alloc = []
