[package]
name = "eva-svc-mailer"
version = "4.0.2"
edition = "2021"

[dependencies]
eva-common = { version = "0.3.23", features = ["events", "time"] }
eva-sdk = { version = "0.3.11" }
tokio = { version = "1.20.1", features = ["full"] }
async-trait = { version = "0.1.51" }
serde = { version = "1.0.143", features = ["derive", "rc"] }
log = "0.4.14"
lettre = { version = "0.10.1", features = ["tokio1-native-tls"] }
jemallocator = { version = "0.5.0" }
once_cell = "1.19.0"
ttl_cache = { version = "0.5" }
parking_lot = "0.12.1"
tokio-task-pool = "0.1.5"
async-channel = "1.7.1"

[features]
std-alloc = []
