[package]
name = "eva-ffi"
version = "4.0.2"
edition = "2021"
publish = false

[dependencies]
busrt = { version = "0.4", features = ["rpc", "ipc"] }
eva-common = { version = "0.3.76", features = ["events", "time"] }
eva-sdk = { version = "0.3.55" }
tokio = { version = "1.36.0", features = ["full"] }
async-trait = { version = "0.1.77" }
serde = { version = "1.0.196", features = ["derive", "rc"] }
log = "0.4.20"
async-channel = "1.9.0"
jemallocator = { version = "0.5.4" }
libloading = "0.8.1"
once_cell = "1.19.0"
clap = { version = "3.2.25", features = ["derive"] }

[features]
std-alloc = []
openssl-vendored = ["eva-common/openssl-vendored", "eva-common/openssl-no-fips"]
openssl3 = ["eva-common/openssl3"]

[profile.release]
strip = true
lto = true
codegen-units = 1
