client:
  server_url: http://server-host:7555/
  # enable FIPS-140 mode
  fips: false
  auth:
    name: test
    key: xxx
report:
  system:
    enabled: true
  # cpu info
  cpu:
    enabled: true
  # system load average
  load_avg:
    enabled: true
  # memory info
  memory:
    enabled: true
  # disk info
  disks:
    enabled: true
    # enable specific mount points only
    # note: for automatic mountpoint list reporting unavailable is not supported
    #mount_points:
      #- /
      #- /var
  # network info
  network:
    enabled: true
    # enable specific interfaces only
    # note: for automatic interface list reporting unavailable is not supported
    #interfaces:
      #- eth0
      #- eth1
