[package]
name = "eva-controller-system"
version = "4.0.2"
edition = "2021"

[dependencies]
busrt = { version = "0.4", features = ["rpc", "ipc"] }
eva-common = { version = "0.3", features = ["events", "time"] }
eva-sdk = { version = "0.3" }
tokio = { version = "1.20.1", features = ["full"] }
async-trait = { version = "0.1.51" }
serde = { version = "1.0.143", features = ["derive", "rc"] }
log = "0.4.14"
async-channel = "1.6.1"
jemallocator = { version = "0.5.0" }
once_cell = "1.19.0"
sysinfo = "0.30.5"
parking_lot = "0.12.1"

[features]
std-alloc = []
