[package]
name = "eva-svc-generator"
version.workspace = true
edition.workspace = true
repository.workspace = true
publish = false

[dependencies]
tokio = { features = ["full"] , workspace = true }
eva-common = { features = ["events", "common-payloads", "payload", "acl", "time"] , workspace = true }
eva-sdk = { workspace = true }
async-trait = { workspace = true }
serde = { features = ["derive", "rc"] , workspace = true }
log = { workspace = true }
mimalloc = { workspace = true }
once_cell = { workspace = true }
busrt = { features = ["rpc", "ipc"] , workspace = true }
rand = "0.8.5"
meval = "0.2.0"
bmart-derive = "0.1.3"
uuid = { features = ["v4"] , workspace = true }
chrono = { workspace = true }

[features]
std-alloc = []
