[package]
name = "eva-db-timescale"
version = "4.0.2"
edition = "2021"

[dependencies]
busrt = { version = "0.4", features = ["rpc", "ipc"] }
tokio = { version = "1.20.1", features = ["full"] }
async-trait = { version = "0.1.51" }
serde = { version = "1.0.143", features = ["derive", "rc"] }
eva-common = { version = "0.3.32", features = ["events", "db", "workers", "common-payloads", "time"] }
log = "0.4.14"
async-channel = "1.7.1"
eva-sdk = { version = "0.3.33" }
once_cell = "1.9.0"
bmart = "0.1.10"
sqlx = { version = "0.6", features = [
  "runtime-tokio-native-tls", "postgres", "chrono" ] }
futures = "0.3.21"
chrono = "0.4.31"
jemallocator = { version = "0.5.0" }

[features]
std-alloc = []
