[package]
name = "eva-repl"
version = "4.0.0"
edition = "2021"

[dependencies]
busrt = { version = "0.3", features = ["rpc", "ipc"] }
eva-common = { version = "0.1.178", features = ["events", "time", "common-payloads"] }
eva-sdk = { version = "0.1.106", features = ["pubsub", "http"] }
tokio = { version = "1.20.1", features = ["full"] }
async-trait = { version = "0.1.51" }
serde = { version = "1.0.143", features = ["derive", "rc"] }
log = "0.4.14"
lazy_static = "1.4.0"
async-channel = "1.7.1"
jemallocator = { version = "0.5.0" }
psrpc = { path = "../../psrpc" }
psrt = "0.1.19"
paho-mqtt = "0.10.0"
serde_json = "1.0.79"
once_cell = "1.10.0"
bmart = "0.1.14"
triggered = "0.1.2"
uuid = { version = "1.1.2", features = ["serde", "v4"] }
wshack = { version = "0.1", path = "../../wshack" }

[features]
std-alloc = []
